config/routes.rb
Rails.application.routes.draw do
  root 'charts#index'
  
  resources :charts do
    resources :songs
  end

  scope 'songs/:song_id', as: 'song' do
    resources :artists
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecor
  has_many :songs
end

app/models/chart.rb
class Chart < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :chart, optional: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update]

  def index
    @artist = Artist.all
  end

  def show
  end

  def edit
  end

  def new
  end

  def create
  end

  end

  def update
  end

  def destroy

  private
  
    def artist_params
      params.require(:artist).permit(:name)
    end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update]

  def index
    @chart = Chart.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def chart_params
    params.require(:chart).permit(:name)
  end

  def set_chart
    @chart = Chart.find(params[:id])
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_chart
  before_action :set_song, only: [:edit, :show, :update, :destroy]

  def show
  end
  
  def new
    @song = @chart.songs.new
  end

  def edit
  end

  def create 
    @song = @chart.songs.new(song_params)
    if @song.save
      redirect_to chart_path(@chart, @song)
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def set_chart
    @chart = Chart.find(params[:chart_id])
  end

  def song_params
    params.require(:song).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/charts/index.html.erb
<h1>Billboard Top Charts!</h1>
<hr />

<table class="ui striped line table">
    <thead>
    <tr>
      <th>Chart Name</th>
    </tr>
  </thead>
  <tbody>
    <th>
      <% @chart.each do |chart|%>
        <%= link_to chart.name, chart_path(chart) %>
        <br />
      <% end %>
    </th>
  </tbody>
</table>

app/views/charts/new.html.erb
<h1>Charts#new</h1>
<p>Find me in app/views/charts/new.html.erb</p>

app/views/charts/show.html.erb
<h1 class='ui header'><%= @chart.name%></h1>

<%= link_to 'Add New Song', new_chart_song_path(@chart) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='ui container'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/songs/new.html.erb
<h1>Hello World</h1>

<%= form_for [@chart, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <%= f.submit 'Add Song', class: 'ui inverted button green'%>
<% end %>

app/views/songs/show.html.erb
<h1> Hello World</h1>